### ISSUE TITLE
Plugin generating incorrect API urls

### ISSUE THREAD

**Issue by div-cowboy** [netlify/netlify-plugin-gatsby#113]
I'm trying to deploy my site to Netlify, but my Gatsby Function API routes are not working. When I go to them directly, I'm served the following error. The only place I have node-fetch is as a dependency of this plugin

https://imgur.com/QK1jUKy

Do I need something special in my toml file besides the plugin import? Appreciate any help/guidance 🙏

**Comment by ascorbic** [comment]
Hi! Sorry you're having trouble. Are you able to share your repo, or a minimal reproduction of the issue?

**Comment by ascorbic** [comment]
I'm closing this as there is no reproduction. If you are still having this problem with version 2 of the plugin, please open a new issue.
