### ISSUE TITLE
Netlify returns HTTP ERROR 500 on DSG pages

### ISSUE THREAD

**Issue by henrik-m** [netlify/netlify-plugin-gatsby#126]
**Describe the bug**

I wanted to test the compatibility of the latest version of Gatsby with Netlify and followed all the steps in the Gatsby documentation and on this plugin's readme page.

Gatsby functions and my SSR test page are working, but accessing one of the DSG pages throws a 500 error. There is nothing logged to the __dsg function log in the Netlify dashboard.

Debugging locally with "netlify dev", all pages are working as expected.

**Steps to reproduce**

1. Create a new Netlify site
2. Set build image and environment variable as documented on this plugin's readme page
3. Deploy from this repository: https://github.com/henrik-m/gatsby4
4. Navigate to https://your-site.netlify.app/dsg/1/

**Expected behavior**

The rendered page shows up. Which is what happens locally with `netlify dev`.

**Environment**

If it helps, my test site on Netlify is https://youthful-fermi-41f243.netlify.app/. (Gets flagged as malicious by Google Chrome, I don't know why. I just created it the other day).

* https://youthful-fermi-41f243.netlify.app/api/test => works
* https://youthful-fermi-41f243.netlify.app/ssr/ => works (or times out, if the 3rd party API call takes too long)
* https://youthful-fermi-41f243.netlify.app/dsg/1 => 500
* https://youthful-fermi-41f243.netlify.app/this-is-nothing/ => 500

I don't know why non-existent routes return 500's as well and if this is part of the problem. Netlify doesn't seem to provide any logs for this.

**Can you submit a pull request?**

No. I cannot even see the actual error in the logs.

**Comment by ascorbic** [comment]
Hey! Thanks for the report. That should be fixed in the latest verison of the build plugin. Run `npm add -D @netlify/plugin-gatsby@beta` to update it. If it doesn't work first time, clear the cache and deploy again.

**Comment by henrik-m** [comment]
@ascorbic Fixed it is! Thank you!
