### ISSUE TITLE
[functions] Must use import to load ES Module: node-fetch

### ISSUE THREAD

**Issue by ezracelli** [netlify/netlify-plugin-gatsby#137]
**Describe the bug**

HTTP 502 Bad Gateway error with the following response body:

```
{
  "errorType": "Error",
  "errorMessage": "Must use import to load ES Module: /var/task/packages/[omitted]/node_modules/node-fetch/src/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/packages/[omitted]/node_modules/node-fetch/src/index.js from /var/task/packages/[omitted]/netlify/functions/gatsby/functions.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/packages/[omitted]/node_modules/node-fetch/package.json.\n",
  "trace": [
    "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/packages/[omitted]/node_modules/node-fetch/src/index.js",
    "require() of ES modules is not supported.",
    "require() of /var/task/packages/[omitted]/node_modules/node-fetch/src/index.js from /var/task/packages/[omitted]/netlify/functions/gatsby/functions.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.",
    "Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/packages/[omitted]/node_modules/node-fetch/package.json.",
    "",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
    "    at Module.require (internal/modules/cjs/loader.js:961:19)",
    "    at require (internal/modules/cjs/helpers.js:92:18)",
    "    at Object.<anonymous> (/var/task/packages/[omitted]/netlify/functions/gatsby/functions.js:3:37)",
    "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)"
  ]
}
```

**Steps to reproduce**

* write gatsby function
* run local `netlify build`
* run local `netlify deploy`
* observe 502 HTTP error with above response body on hitting `/api/xxx` endpoint

OR

* write gatsby function
* `git push`
* use built-in netilfy CI pipeline
* observe 502 HTTP error with above response body on hitting `/api/xxx` endpoint

**Expected behavior**

the function should call the defined gatsby handler without error

**Configuration**

`package.json`:

```json
{
  "dependencies": {
    "gatsby": "3.14.0"
  },
  "devDependencies": {
    "@netlify/plugin-gatsby": "1.0.3",
    "gatsby-plugin-netlify": "3.14.0",
    "netlify-cli": "6.9.28"
  }
}

```

`netlify.toml`:

```toml
[build]
command = "gatsby build"
publish = "public"

[[plugins]]
package = "@netlify/plugin-gatsby"
```

file structure:

```
src
-- functions
---- xxx.ts
```

commands to build/deploy:

```bash
$ netlify build
$ netlify deploy --prod
$ curl https://xxx.netlify.app/api/xxx
```

**Can you submit a pull request?**

**Yes**, happy to! Not too sure where to start though, this seems like it's coming from the template.

**Comment by ascorbic** [comment]
Hi. Can you try updating the netlify cli and rebuilding. When building locally, do `netlify deploy --build --prod` rather than a separate build step

**Comment by ezracelli** [comment]
@ascorbic unfortunately the issue persists when using the latest netlify cli, and it's also replicable using Netlify's built in CI rather than running the build on my local. Looks like it's related to `node-fetch`'s move to an ESM-only distribution: node-fetch/node-fetch#1279

Writing this response actually helped me get this solved &mdash; apparently, another dependency in my project also had a dependency on `node-fetch`, but `@^3.0.0` (the ESM version), rather than `@^2.6.1` (the CJS version), which `@netlify/plugin-gatsby` requires. For whatever reason, the Node resolution algorithm pulled in v3 rather than v2 to the functions bundle, leading to this error. To solve, I added `node-fetch@^2.6.1` to my root `package.json`, forcing the resolution algorithm to pull in that version instead of v3.

**Comment by ascorbic** [comment]
Ah, that's great. Glad you got it sorted
