### ISSUE TITLE
Don't create `/api/` redirect unless there are Gatsby Functions in the site

### ISSUE THREAD

**Issue by Elyx0** [netlify/netlify-plugin-gatsby#166]
From https://github.com/netlify/netlify-plugin-gatsby/blob/main/plugin/src/index.ts#L107-L112

This plugin uses redirects to override `/api` but it's a common entry point when making serverless functions.
Is there any way to make it so it it's an option from the .toml?

**Comment by ascorbic** [comment]
HI @Elyx0 ,
This is a path defined by Gatsby, which uses it for Gatsby Functions. What we could do is check if there are any functions before adding that redirect

**Comment by Elyx0** [comment]
This looks like a nice idea. As well as some more logging during the plugin lifecycle, like outputting the final redirects file if needed by a verbose plugin input. I struggled to guess its final state after build. (or even find it to read it from a function run)
