### ISSUE TITLE
Failing build: Failed to upload file: __ssr Failed to upload file: __dsg

### ISSUE THREAD

**Issue by d4v1d82** [netlify/netlify-plugin-gatsby#167]
**Describe the bug**

Build fails for `gatsby v4.1.0` and `@netlify/plugin-gatsby@2.0.0-zz-beta.0` while works with stable version of @netlify/plugin-gatsby (of course without dsg and ssr)

Here the logs:
```
10:54:59 AM: ────────────────────────────────────────────────────────────────
10:54:59 AM:   6. Deploy site                                                
10:54:59 AM: ────────────────────────────────────────────────────────────────
10:54:59 AM: ​
10:54:59 AM: Starting to deploy site from 'public'
10:55:14 AM: Creating deploy tree asynchronously
10:55:14 AM: Creating deploy upload records
10:55:20 AM: 79 new files to upload
10:55:20 AM: 3 new functions to upload
10:55:26 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:26 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:28 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:28 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:30 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:30 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:31 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:32 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:34 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:35 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:38 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:38 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:42 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:42 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:50 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:51 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:58 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:55:59 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:12 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:18 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:23 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:34 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:51 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:56:51 AM: Failed to upload file: __ssr
10:56:52 AM: Failed to upload file: __dsg
10:56:52 AM: Site deploy was successfully initiated
10:56:52 AM: Execution cancelled
10:56:52 AM: Error running command: Command was cancelled
10:56:52 AM: Failing build: Failed to build site
```

**Environment**
  Netlify CI:
     node v14.18.1 (npm v6.14.15)
     @netlify/build 18.21.3
  npmPackages:
    @netlify/plugin-gatsby: ^2.0.0-beta => 2.0.0-zz-beta.0 
    gatsby: ^4.1.0 => 4.1.0

**Comment by QFDigital-team** [comment]
i'm facing the same issue, Failed to upload file: __dsg

**Comment by shameer-rahman** [comment]
i'm facing the same issue, Failed to upload file: __dsg

**Comment by wutangpaul** [comment]
Same issue on Netlify CI with:
...
"@netlify/plugin-gatsby": "^2.0.0-zz-beta.0"
"gatsby-plugin-netlify": "^4.0.0-next.0"
...

````
6:38:27 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
6:38:36 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
6:38:39 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
6:38:52 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
6:38:52 PM: Failed to upload file: __ssr
6:39:21 PM: Failed to upload file: __dsg
6:39:21 PM: Site deploy was successfully initiated
6:39:21 PM: Execution cancelled
6:39:21 PM: Error running command: Command was cancelled
6:39:21 PM: Failing build: Failed to build site
6:39:21 PM: Finished processing build request in 12m26.931180725s
````

**Comment by chrisq21** [comment]
The problem appears to be that the ssr files that Netlify generates (found in `.netlify/functions/__ssr.zip` when running a build on Netlify) **exceed a ~64mb limit** that is imposed by AWS Lambda. Here's an answer in a Netlify forum that states this: [netlify forum link](https://answers.netlify.com/t/request-must-be-smaller-than-69905067-bytes-for-the-createfunction-operation/19104/2).

I believe this SSR functionality is treated as a [Netlify Serverless Function](https://docs.netlify.com/functions/overview/) which ultimately becomes an AWS Lambda function.

Unfortunately I'm not sure what files are ultimately added to the `__ssr.zip` file so I'm not sure how to reduce it's size. @ascorbic Could you offer additional insight or any ideas for reducing the `__ssr.zip` file size?

Note: I added the code below to my `netlify.toml` file, but the total size of my `ssr.zip` is current 81mb.
`[functions]
  node_bundler = "esbuild"`

**Comment by chrisq21** [comment]
For anyone interested in determining their Netlify function/ssr size here's a useful guide (not an official Netlify guide): [article link](https://aboutmonica.com/blog/how-to-check-bundled-netlify-function-size-locally/).

**Comment by ascorbic** [comment]
Hi. Are you able to see what the large files are in the zip?

**Comment by chrisq21** [comment]
The largest folder seems to be `__ssr/.cache/page-ssr/routes/`. If I understand correctly, this data comes from the `.cache` folder that gatsby generates, and the `routes` folder contains the page data for every page that gatsby generates (~200 pages in my case).

![Screen Shot 2022-01-20 at 5 17 17 PM](https://user-images.githubusercontent.com/5369473/150431024-6649c4b4-b144-4fc5-99b6-616aa1281a2c.png)

With my current setup, I'm server-rendering only 1 page and statically generating the rest, but it seems that the data for every page is included in the `__ssr` folder which then exceeds the Lambda limit.

**Comment by ascorbic** [comment]
OK, thanks for the detail. I'm working on the plugin right now, so wil be looking into that too

**Comment by shameer-rahman** [comment]
@ascorbic, thanks for addressing this issue, however after the updating the plugin i still get the same error
```
12:35:00 PM:   5. @netlify/plugin-gatsby (onPostBuild event)                 
12:35:11 PM: The function zip ../../../tmp/zisi-61f8f946bf9f477e6f6d154b/__dsg.zip size is 144 MB, which is larger than the maximum supported size of 52.4 MB.
12:35:11 PM: There are a few reasons this could happen, such as accidentally bundling a large dependency or adding lots of files to "included_files".
12:37:58 PM: Failed to upload file: __ssr
12:38:16 PM: Failed to upload file: __dsg
12:38:16 PM: Site deploy was successfully initiated
12:38:17 PM: Execution timed out after 25m55.148694295s
12:38:17 PM: Error running command: Command did not finish within the time limit
12:38:17 PM: Failing build: Failed to build site
12:38:17 PM: Finished processing build request in 26m40.773676931s
```

**Comment by ascorbic** [comment]
Hi @shameer-rahman ,
Thanks for the update. I'm going to put some more thought into how we can best deal with this.
