### ISSUE TITLE
add logging to indicate best practice is to avoid asset optimization if you use this plugin

### ISSUE THREAD

**Issue by fool** [netlify/netlify-plugin-gatsby#208]
per our internal slack discussion in this thread:  https://netlify.slack.com/archives/C012GT6MYKU/p1639493015033400

cc @ascorbic

**Comment by nickytonline** [comment]
Was this ever looked at @ascorbic @fool?

**Comment by ascorbic** [comment]
Turns out that it's not possible to do, because the optimization config value isn't available in the build.

**Comment by nickytonline** [comment]
OK, thanks @ascorbic. I'm going to go ahead and close this then.
