### ISSUE TITLE
Remove check to ensure .cache/json folder exists

### ISSUE THREAD

**Issue by nickytonline** [netlify/netlify-plugin-gatsby#214]
Thanks for suggesting a new feature!

Please fill in the sections below.

This is not an enhancement, more of a code cleanup.

#124 ensured the .cache/json folder existed, but this appears to no longer be necessary based on the fix in https://github.com/gatsbyjs/gatsby/pull/33431 (merged in October 2021) that resolved https://github.com/gatsbyjs/gatsby/issues/33262.

**Describe the solution you'd like**

Revert #124 as this check is no longer necessary.

**Describe alternatives you've considered**

N/A

**Can you submit a pull request?**

Yes.

Pull requests are welcome! If you would like to help us add this feature, please
check our [contributions guidelines](../blob/master/CONTRIBUTING.md).

**Comment by ascorbic** [comment]
Thanks, @nickytonline! We'll get this done in the next release
