### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by marcomiduri** [netlify/netlify-plugin-gatsby#216]
I have a gatsby website that uses following dependencies:
```
"gatsby-plugin-netlify": "^4.0.0-next.0",
"@netlify/plugin-gatsby": "^2.0.0-beta",
"netlify-lambda": "^2.0.5",
"gatsby": "^4.4.0",
```

I added `gatsby-plugin-netlify` into `gatsby-config.js` file as well.
I installed Essential Gatsby plugin on Netlify and setup the _redirect file in static directory like this:
```
/api/* /.netlify/functions/:splat 200
```

Here's the build log:
https://app.netlify.com/sites/owyn-dev/deploys/61d5e257ba53870008adcd28#L405

This is the request curl command that I use for testing:

```sh
curl --location --request POST 'https://deploy-preview-444--owyn-dev.netlify.app/api/cart/' \
--header 'Content-Type: application/json' \
--header 'Cookie: cartId=73a03db428934ea9b73cbce5460a6396' \
--data-raw '[
    {
        "quantity": 1,
        "variantId": "41001415540924"
    }
]'
```

But this redirect configuration doesn't work on staging website. I need help on this asap.

Thank you

**Comment by ascorbic** [comment]
Hi. Are these Gatsby functions or Netlify functions that you are using? Gatsby 3+ expects that the `/api` path is used for Gatsby Functions, so you shouldn't use your own rewrites

**Comment by marcomiduri** [comment]
@ascorbic Oh, thank you. I've been using Netlify function only. So I don't have that knowledge. Before we install the plugins, it worked fine. Does the Essential Gatsby plugin allow Gatsby function in Netlify? If so, what is the best practice for hiding the /.netlify/functions/ URL in API endpoints.

**Comment by ascorbic** [comment]
Hey. Yes, the Essential plugin adds support for Gatsby Functions. You best bet would be to just use a different prefix, rather than `/api`, or add ones specific for each function rather than using a splat

**Comment by marcomiduri** [comment]
@ascorbic Thank you
