### ISSUE TITLE
Can't overwrite environment variables set in Netlify UI

### ISSUE THREAD

**Issue by jdesherlia** [netlify/netlify-plugin-gatsby#217]
Thanks for reporting this bug!

If this is related to a typo or the documentation being unclear, please click on
the relevant page's `Edit` button (pencil icon) and suggest a correction
instead.

Please search other issues to make sure this bug has not already been reported.

Then fill in the sections below.

**Describe the bug**

With this build plugin enabled, I am no longer able to overwrite environment variables that are set in the netlify UI. We have two variables, one called ENVKEY and another called ENVKEY_DEV. We have been using build contexts and branch names to determine when we might be in a situation to swap one for the other, at which point we do `process.env.ENVKEY = process.env.ENVKEY_DEV`. With this build plugin enabled, this operation no longer works, and the original value is retained.

**Steps to reproduce**

1. Set two secrets in the Netlify UI
2. Place the following lines somewhere near the beginning of your build command:
```
process.env.KEY_1 = process.env.KEY_2
console.log( process.env.KEY_1 )
```

**Expected behavior**

process.env.KEY_1 should now have the value from process.env.KEY_2, but it does not.

**Configuration**

We are running `gulp build && gatsby build` for our build command, ( gulp is for processing our functions ), but I don't think it really matters what command is being run. We are using dotenv in both gulp and gatsby, with this command:
```
require( `dotenv` ).config({
  path: `.env`,
})
```

**Environment**

This only happens when building on Netlify's build system. Locally, it works as expected.

**Screenshots**

In the screenshot below, the end of the highlighted line should say develop, not production:
![image](https://user-images.githubusercontent.com/51459392/148502417-f6d6decb-f13d-463e-8ec8-bcec9d0d3940.png)

**Can you submit a pull request?**

No.

**Comment by jdesherlia** [comment]
Hello. Any update on this?

**Comment by nickytonline** [comment]
Is this still an issue for you @jdesherlia ?

**Comment by jdesherlia** [comment]
I just tried this again, and it seems to be resolved now. Closing. Thanks!
