### ISSUE TITLE
Does not deploy Lambda function when Netlify redirects are defined

### ISSUE THREAD

**Issue by screendriver** [netlify/netlify-plugin-gatsby#230]
**Describe the bug**

First I'm not 100% sure if this is a bug with Netlify (the Netlify CLI itself) or if it's related to this plugin. So hopefully someone with more insights can help here: when there is already a `_redirects` file defined in the `static/` directory this plugin indeed does create correctly the following entry at the end of the file

```
## Created with gatsby-plugin-netlify
/foo/*  /  301
# @netlify/plugin-gatsby redirects start
/api/* /.netlify/functions/gatsby 200
# @netlify/plugin-gatsby redirects end
```

**but** the Lambda function itself is not deployed. From the Netlify CLI I'm getting

```sh
(Netlify Build completed in 3m 26.6s)
Deploy path:        /Users/me/Workspace/some-site/public
Configuration path: /Users/me/Workspace/some-site/netlify.toml
Deploying to draft URL...
✔ Finished hashing 4242 files
✔ CDN requesting 42 files
✔ Finished uploading 42 assets
✔ Deploy is live!
```

When I **completely** remove the `static/_redirects` file the Netlify CLI output is

```sh
(Netlify Build completed in 3m 31.2s)
Deploy path:        /Users/me/Workspace/some-site/public
Functions path:     /Users/me/Workspace/some-site/netlify/functions
Configuration path: /Users/me/Workspace/some-site/netlify.toml
Deploying to draft URL...
✔ Deploying functions from cache (use --skip-functions-cache to override)
✔ Finished hashing 4242 files and 1 functions
✔ CDN requesting 42 files and 0 functions
✔ Finished uploading 42 assets
✔ Deploy is live!
```

On the third line there is the indicator that the function is found and deployed. I'm using additionally `gatsby-plugin-netlify` in combination with `@netlify/plugin-gatsby`.

**Steps to reproduce**

1. create a new Gatsby project
2. create a Lambda function in `src/api/`
3. create a `static/_redirects` file with one or more redirects. For example `/foo/*     /      301`
4. build the project with `npx netlify deploy --build`

The same happens when a `_redirects` file is **not** present but created programatically in `gatsby-node.js` with

```js
exports.createPages = async ({ actions }) => {
  const { createRedirect } = actions;

  createRedirect({
    fromPath: '/foo/*',
    toPath: '/',
    statusCode: 301,
  });
};
```

**Expected behavior**

A Netlify Lambda function should be deployed

**Configuration**

- 

**Environment**

```bash
$ npx envinfo --system --binaries --browsers --npmPackages @netlify/plugin-gatsby

  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 2.16 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/85/8rb_y49j5911bg5qzd7tkddw0000gp/T/fnm_multishells/78765_1642439901724/bin/node
    npm: 8.1.2 - /var/folders/85/8rb_y49j5911bg5qzd7tkddw0000gp/T/fnm_multishells/78765_1642439901724/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.62
    Firefox Developer Edition: 92.0
    Safari: 15.2
  npmPackages:
    @netlify/plugin-gatsby: 1.0.3 => 1.0.3
```

plus I'm using `"gatsby-plugin-netlify": "3.14.0"` and Gatsby v3 (`3.14.5`)

**Screenshots**

-

**Can you submit a pull request?**

No.

**Comment by ascorbic** [comment]
Hi. Can you try with `@netlify/plugin-gatsby@next`?

**Comment by screendriver** [comment]
There is no [@netlify/plugin-gatsby@next](https://www.npmjs.com/package/@netlify/plugin-gatsby). And the latest `@beta` was published 4 months ago.

**Comment by ascorbic** [comment]
Can you try again with the latest version?

**Comment by screendriver** [comment]
Do you mean `2.0.2` of `@netlify/plugin-gatsby`? This gives me

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-projecte@1.0.0
npm ERR! Found: common-tags@1.8.0
npm ERR! node_modules/common-tags
npm ERR!   dev common-tags@"1.8.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer common-tags@"^1.8.2" from @netlify/plugin-gatsby@2.0.2
npm ERR! node_modules/@netlify/plugin-gatsby
npm ERR!   dev @netlify/plugin-gatsby@"2.0.2" from the root project
```

When I do `npm install --legacy-peer-deps` the installation seems to work. But then I get following message during build time:

```sh
❯ Loading plugins
   - @netlify/plugin-gatsby@2.0.2 from netlify.toml and package.json

❯ Incompatible plugins
   - @netlify/plugin-gatsby@2.0.2: version 1.0.3 is the most recent version compatible with gatsby@<4.0.0
```

And `v1.0.3` is already the version that I have.

**Comment by screendriver** [comment]
Looks good now. However I've updated to Gatsby 4 in the meantime.
