### ISSUE TITLE
Error: Cannot find module 'lmdb-store'

### ISSUE THREAD

**Issue by t2ca** [netlify/netlify-plugin-gatsby#291]
I'm getting this error with the Gatsby 4.8.0

Gatsby 4.8.0 has upgrade from `lmdb-store` to `lmdb`

```
Error: Cannot find module 'lmdb-store'
Require stack:
- /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/helpers/files.js
- /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/index.js
```

**Comment by ascorbic** [comment]
Hi. Can you confirm that this is just a log, and that the build still completes? We should be handling this [here](https://github.com/netlify/netlify-plugin-gatsby/blob/main/plugin/src/helpers/files.ts#L103-L106) (though I should hide the error message).

**Comment by ascorbic** [comment]
Is this deployed from your local machine, or via Netlify CI?

**Comment by t2ca** [comment]
Netlify

[https://www.t2.ca/test-ssr/](https://www.t2.ca/test-ssr/)

**Comment by ascorbic** [comment]
Thanks. I'm going to move this to a new issue, as it seems to be unrelated.
