### ISSUE TITLE
`/lib/templates/api/gatsbyFunction.js` file seems corrupt

### ISSUE THREAD

**Issue by kvnang** [netlify/netlify-plugin-gatsby#310]
**Describe the bug**

When deploying Gatsby site with @netlify/plugin-gatsby 2.1.0+, build fails with the following error.

```
Could not import plugin:
/opt/build/repo/node_modules/@netlify/plugin-gatsby/lib/templates/api/gatsbyFunction.js:1

SyntaxError: Invalid or unexpected token
```

**Comment by ascorbic** [comment]
Thanks for the report! There seems to have been a file corrupted during publish. I've released 2.1.2, which fixes it.
