### ISSUE TITLE
Could not import plugin (v 2.1.1 on netlify.app)

### ISSUE THREAD

**Issue by eightshone** [netlify/netlify-plugin-gatsby#311]
Thanks for reporting this bug!

If this is related to a typo or the documentation being unclear, please click on
the relevant page's `Edit` button (pencil icon) and suggest a correction
instead.

Please search other issues to make sure this bug has not already been reported.

Then fill in the sections below.

**Describe the bug**

I was deploying some updates for a project using gatsby's default wordpress starter. The last successful deploy was on march 1st

**Steps to reproduce**

I really don't know how to reproduce this one! Even the failed builds (not related to the plugin) got past the loading of the plugin and even retrieved data from my source.

**Expected behavior**

Plugin should load.

**Configuration**

Command line options and/or configuration file, if any.

**Environment**

Enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --browsers --npmPackages @netlify/plugin-gatsby
```
this is from the Netlify output
![image](https://user-images.githubusercontent.com/36240779/156468212-fb83847b-e93c-415f-9c87-961477fb5c10.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36240779/156468150-0b1a939a-d9f2-4271-949a-5dc255124e1c.png)

**Can you submit a pull request?**

No.

**Comment by t2ca** [comment]
I can confirm I also have the same issue with v2.1.1

**Comment by grandrepublic** [comment]
I am also seeing this error. Happened after my build switched from using 2.0.3 -> 2.1.1

**Comment by tianheg** [comment]
have tested: v2.1.0 works

**Comment by sergio-ortiz** [comment]
Same thing here, I quickly uninstalled the plugin from the Netlify UI and the problem seemed to go away.

**Comment by grgcnnr** [comment]
Also seeing this behaviour

**Comment by ascorbic** [comment]
Hi. This is fixed it 2.1.2. It was caused by a corrupted file in the published package. See #310

**Comment by ryotaro-tenya0727** [comment]
I got same error, I can resolve `"@netlify/plugin-gatsby": "2.0.4"` in package.json

Thank you

**Comment by eightshone** [comment]
@ascorbic thank you for the fix. Netlify is still suing 2.1.1 (I just checked). I will include the package explicitly in my packages until netlify change the version to 2.1.2
I don't know if I should close the issue or not tho?

**Comment by sergio-ortiz** [comment]
> 
Might be old news but, I just wanted to say that Netlify is now using 2.1.2.

**Comment by eightshone** [comment]
@sergio-ortiz you are right. I was about to close this issue.

**Comment by ascorbic** [comment]
Thanks everyone for your patience and help spotting this so quickly.
