### ISSUE TITLE
Optionally load Gatsby datastore into lambdas after deploy

### ISSUE THREAD

**Issue by ascorbic** [netlify/netlify-plugin-gatsby#320]
We currently include the Gatsby lmdb datastore (data.mdb) in the lambda bundle, then move it into the tmp dir at first run, because it needs to be in a writeable filesystem. The problem with this is that for large sites the database can be larger than the maximum lambda deploy size. We could avoid this by instead loading the db from the CDN at first run. This would mean its size would be limited only by the max tmp dir size (512MB), but it would have a cold start cost. It would also mean the db was technically exposed to the internet. However if we create a filename that is very long and random then that is equivalent to password protection. The filename could be bundled inside the lambda instead, along with a hash of the file.

Because of the tradeoff, it would make sense for this to be optional. We could either do it automatically if we see the datastore is larger than a certain size, or we could use an env var and give an error message that suggests enabling it if the db is too large.

**Comment by ascorbic** [comment]
Some notes from our discussion:

- we could set headers config to add basic auth to the db file too
- we could pre-warm the lambda in an `onSuccess` call, which would ensure the db was loaded before the first request

**Comment by fool** [comment]
Enterprise customer excited for the fix:  https://netlify.zendesk.com/agent/tickets/92557

**Comment by shafraj** [comment]
Hi team, 

Adding in from the Account Management side, this customer is Pan Macmillan and they are up for renewal next month.

This roadblock is causing a churn risk in that they can't reliably deploy Gatsby 4 on Netlify. 

They are now evaluating Gatsby Cloud, this issue right around renewal time poses a risk for us to lose this strategic account.

Any insight on timeline for a fix is greatly appreciated, we'll be meeting with them next week to discuss as well. 

Thank you!

CC: @rsedighi

**Comment by rjbeers** [comment]
FYI, Riot is interested in using DSG at some point to further improve build times. For the playvalorant site, their data.mdb file was over 2GB uncompressed. Looks like the proposed solution would be capped at 512MB, so wouldn't be sufficient for them.

**Comment by krider2010** [comment]
As a slight widening of scope here, if changes to the DB can be made independently to the rest of the build that would be a huge value add to our customers. It might require some work from Workflow folks but please include this in your conversations.

For more context reach out to me (or technically) @ascorbic .

**Comment by ericapisani** [comment]
@krider2010 I've created a separate issue for the work that you mentioned [here](https://github.com/netlify/netlify-plugin-gatsby/issues/377) and assigned @ascorbic so he can fill out the details when some thought has been given to how we want to approach that

**Comment by ericapisani** [comment]
Just to give an update here - main functionality has been released, currently working on the documentation for this

**Comment by nickytonline** [comment]
Looks like the documentation is done. Is there anything else left for this issue @ericapisani or is it OK to close this?

**Comment by ericapisani** [comment]
It's ok to close this now
