### ISSUE TITLE
Update pull request template

### ISSUE THREAD

**Issue by ascorbic** [netlify/netlify-plugin-gatsby#326]
The PR template should match the one from netlify-plugin-gatsby

**Comment by robations** [comment]
> The PR template should match the one from netlify-plugin-gatsby

Is that a typo? This project _is_ netlify-plugin-gatsby.

Perhaps meaning to match the templates here?

https://github.com/netlify/build-plugin-template/tree/master/.github

**Comment by ascorbic** [comment]
Yeah, I meant netlify-plugin-nextjs
