### ISSUE TITLE
Gatsby SSR pages returns 404 when deployed to Netlify

### ISSUE THREAD

**Issue by dcheepurupalli** [netlify/netlify-plugin-gatsby#332]
Gatsby SSR page returns 404 error when deployed to Netlify. Locally, it works as expected.

Repo : https://github.com/dcheepurupalli/gatsby-starter-rendering-modes
Netlify URL: https://reverent-johnson-e551da.netlify.app
SSR Page : https://reverent-johnson-e551da.netlify.app/ssr

**Comment by ascorbic** [comment]
Hi @dcheepurupalli 
Have you installed `gatsby-plugin-netlify`? It's required for SSR to work

**Comment by dcheepurupalli** [comment]
No @ascorbic. Added just now and it's working now. Thank you so much.

**Comment by ascorbic** [comment]
Great! Thanks for letting me know
