### ISSUE TITLE
Plugin "@netlify/plugin-gatsby" failed

### ISSUE THREAD

**Issue by nsalow32** [netlify/netlify-plugin-gatsby#335]
I'm very new at this and am unsure how to fix the problem, or if I'm providing the correct information. I would appreciate any help!

2:13:57 PM:   Plugin "@netlify/plugin-gatsby" failed                        
2:13:57 PM: ────────────────────────────────────────────────────────────────
2:13:57 PM: ​
2:13:57 PM:   Error message
2:13:57 PM:   SyntaxError: Could not load gatsby-config.js
2:13:57 PM:   /opt/build/repo/src/util/site.json: Unexpected string in JSON at position 301
2:13:57 PM: ​
2:13:57 PM:   Plugin details
2:13:57 PM:   Package:        @netlify/plugin-gatsby
2:13:57 PM:   Version:        2.1.4
2:13:57 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-gatsby.git
2:13:57 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-gatsby
2:13:57 PM:   Report issues:  https://github.com/netlify/netlify-plugin-gatsby/issues
2:13:57 PM: ​
2:13:57 PM:   Error location
2:13:57 PM:   In "onPreBuild" event in "@netlify/plugin-gatsby" from netlify.toml
2:13:57 PM: ​
2:13:57 PM:   Resolved config
2:13:57 PM:   build:
2:13:57 PM:     command: npm run build
2:13:57 PM:     commandOrigin: config
2:13:57 PM:     environment:
2:13:57 PM:       - NODE_VERSION
2:13:57 PM:     publish: /opt/build/repo/public
2:13:57 PM:     publishOrigin: config
2:13:57 PM:   plugins:
2:13:57 PM:     - inputs: {}
2:13:57 PM:       origin: config
2:13:57 PM:       package: '@netlify/plugin-gatsby'
2:13:57 PM: Caching artifacts
2:13:57 PM: Started saving node modules
2:13:57 PM: Finished saving node modules
2:13:57 PM: Started saving build plugins
2:13:57 PM: Finished saving build plugins
2:13:57 PM: Started saving yarn cache
2:14:05 PM: Finished saving yarn cache
2:14:05 PM: Started saving pip cache
2:14:05 PM: Finished saving pip cache
2:14:05 PM: Started saving emacs cask dependencies
2:14:05 PM: Finished saving emacs cask dependencies
2:14:05 PM: Started saving maven dependencies
2:14:06 PM: Creating deploy upload records
2:14:05 PM: Finished saving maven dependencies
2:14:05 PM: Started saving boot dependencies
2:14:05 PM: Finished saving boot dependencies
2:14:05 PM: Started saving rust rustup cache
2:14:05 PM: Finished saving rust rustup cache
2:14:06 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:14:05 PM: Started saving go dependencies
2:14:05 PM: Finished saving go dependencies
2:14:05 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:14:06 PM: Failing build: Failed to build site
2:14:06 PM: Finished processing build request in 1m8.908610378s

**Comment by ascorbic** [comment]
The logs indicate the problem is with the file `util/site.json`. This isn't something the plugin uses or creates. Does that file exist in your site? If so, is it valid JSON?

**Comment by nsalow32** [comment]
@ascorbic thank you! 
I have altered that, but only the variables (I think) to customize it. I'm not sure what I did to cause the error? My personal URL is linked to the site, and I thought maybe changing that in site.JSON was the issue. I changed it back to the template and that didn't fix the issue. I haven't worked with JSON before, so I probably created some kind of error.

I'm also not sure if there is something that should be replacing this:   "ga": "UA-XXXXXXXXX-X" that's causing the issue.

Here is the code for that page:
[](https://github.com/){
  "meta": {
    "title": "Nicole Salow",
    "titleTemplate": "%s",
    "siteUrl": "https://foundation.stackrole.com",
    "description": "A talented graphic designer ready to work!",
    "image": "/assets/stackrole.png",
    "iconimage": "/assets/stackrole.png",
    "twitterUsername": "@stackrole"
    "instagram": "@coleycreative"
  },
  "ga": "UA-XXXXXXXXX-X"
}

**Comment by nsalow32** [comment]
Something so simple... I still have a lot to learn, thank you so much!

**Comment by ascorbic** [comment]
No worries! Glad I could help. Can you confirm that it fixes this?

**Comment by nsalow32** [comment]
Yes, the site loaded with no issues. Thanks!
