### ISSUE TITLE
[Bug]: Image stuff not being enabled

### ISSUE THREAD

**Issue by raae** [netlify/netlify-plugin-gatsby#372]
### Summary

My site usepow.app (pow-site is the Netlify id) stopped working with Gatsby Image CDN. 

@ascorbic said in convo:
> It looks from your logs that none of tyhe image stuff is being enabled

It worked at one point after I set `GATSBY_CLOUD_IMAGE_CDN` to true in the UI, then it stopped.

### Steps to reproduce

1. Got to usepow.app
2. Scroll to the bottom
3. Observe black squares

### Plugin version

3.0.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Configuration

<details>
  <summary>`gatsby-config.js` and options</summary>
  
```
# Paste content of your `gatsby-config.js` file, and/or command line options here. Check there is no private info in there.
```

</details>

### Environment

<details>
  <summary>Environment</summary>
  
```
# Paste output from `npx envinfo` here.
```

</details>

### Gatsby info

<details>
  <summary>gatsby info</summary>
  
```
# Paste output from `gatsby info` here.
```

</details>

### Your _redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

**Comment by orinokai** [comment]
Hi @raae, I'd like to look into this further. Are you able to provide a reproduction repo that I can look at?

**Comment by raae** [comment]
The repo is [olavea/pow-site](https://github.com/olavea/pow-site) @orinokai and works locally. It also worked on Netlify up 

Works: https://app.netlify.com/sites/pow-site/deploys/626bdcfe43615700088164e3
Does not work: https://app.netlify.com/sites/pow-site/deploys/627200a58d3c77000821e1d6

Change in code: https://github.com/olavea/pow-site/compare/f64fe2d..0ef77b9

Might be that adding gatsby-plugin-netlify messed things up?

**Comment by raae** [comment]
I also did a clone and tries 3-4 times and not seeing any issues with the images locally. It's only the YouTube Thumbnails that use the Gatsby Image CDN.

Did you see @ascorbic comment about "It looks from your logs that none of tyhe image stuff is being enabled"?

**Comment by raae** [comment]
The images are coming through this plugin: https://github.com/queen-raae/gatsby-source-youtube-oembed. It has a demo site and I deployed it to Gatsby Cloud and Netlify. It works on Gatsby Cloud and not on Netlify. 

https://sweet-shortbread-13a460.netlify.app/
https://gatsbysourceyoutubeoembedmain.gatsbyjs.io/ (it takes a tiny bit to load)

I enabled Image CDN the same way as for the pow-site using `GATSBY_CLOUD_IMAGE_CDN` to true in the UI. Am I doing it wrong?

**Comment by orinokai** [comment]
I was able to get the demo site to work by creating a site with the following settings:

base directory = `demo`
build command = `gatsby build`
publish directory = `demo/public`

`GATSBY_CLOUD_IMAGE_CDN` = true
`NETLIFY_USE_YARN` = true

https://rs-test-gatsby-source-youtube-oembed.netlify.app
