### ISSUE TITLE
Modify the datastore independently of the rest of the build

### ISSUE THREAD

**Issue by ericapisani** [netlify/netlify-plugin-gatsby#377]
**Which problem is this feature request solving?**

Original comment: https://github.com/netlify/netlify-plugin-gatsby/issues/320#issuecomment-1124880268

**Describe the solution you'd like**

TBD

Example: This could be fixed by [...]

**Describe alternatives you've considered**

Example: Another solution would be [...]

**Can you submit a pull request?**

Yes/No.

Pull requests are welcome! If you would like to help us add this feature, please
check our [contributions guidelines](../blob/master/CONTRIBUTING.md).

**Comment by ascorbic** [comment]
This is different from the other issue. It's about being able to update the database without deploying a new build. It's pretty vague right now though, so I'm ok with closing this, but it's @ericapisani's call

**Comment by ericapisani** [comment]
I think due to other things taking higher priority (and no requests for this at the moment), we can close this for now and reopen if we need to in the future
