### ISSUE TITLE
Fix issues with the CI build process

### ISSUE THREAD

**Issue by MarcL** [netlify/netlify-plugin-gatsby#443]
**Which problem is this feature request solving?**

For a few recent pull requests there have been some difficulties with broken CI builds. This is due to incorrect synchronisation of the `package.json` and `package-lock.json` files during the `npm ci` installation process during the GitHub actions workflow.

In addition, there's a need to correctly install the package dependencies in both the main project and both of the `/plugin` and `/demo` folders if working on it locally. The dependency exists during the execution of the `lint:*` and `test:*` scripts.

**Describe the solution you'd like**

We should try to minimise confusion during the installation process. This should be correctly document.
We should also investigate the correct build steps to ensure that the package files remain in sync.

**Describe alternatives you've considered**

We could consider whether this plugin repository might benefit from becoming a monorepo similar to the [netlify/netlify-plugin-nextjs](https://github.com/netlify/netlify-plugin-nextjs) plugin. Using `npm` workspaces may be useful here.

**Can you submit a pull request?**

Yes - eventually!

**Comment by MAU-Estate** [comment]
@MarcL thanks for adding this issue. I believe this is the reason my build keeps failing on Netlify from the repo but not when running `netlify build` or `netlify deploy` locally.

Are there any known workarounds?

**Comment by MarcL** [comment]
Hi @MAU-Estate.

Can you open an issue in this repo, please?
It'll give us some more details and logs and make it easier to debug for you.
Thanks!

**Comment by MAU-Estate** [comment]
Done. Added at URL below. Thanks @MarcL 

[[Bug]: Build has been failing for over a year on live website- only local netlify CLI deploys work](https://github.com/netlify/netlify-plugin-gatsby/issues/601)

**Comment by MarcL** [comment]
Looks like the linked bug has a fix so closing this.
