### ISSUE TITLE
Update README to include information on adding Background Functions to a site

### ISSUE THREAD

**Issue by ericapisani** [netlify/netlify-plugin-gatsby#451]
It's not entirely clear how to set up [Background Functions](https://docs.netlify.com/functions/background-functions/) to a Gatsby site.

We should add a section to this project's README telling users how to do so

Related issue: https://github.com/netlify/netlify-plugin-gatsby/issues/436

Related documentation:
* https://docs.netlify.com/functions/background-functions/
* https://docs.netlify.com/functions/build-with-javascript/#background-function-format

**Comment by ascorbic** [comment]
Might as well add info for scheduled functions at the same time, as the process is the same
