### ISSUE TITLE
Issue with linking github organizations

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [netlify/netlify-plugin-gatsby#543]
Hello everybody,

I am opening an issue here because I have been facing this issue for a while now and couldn't get hold of any netlify employees to help.

When I click on Add another organization:
![image](https://user-images.githubusercontent.com/41989385/200066469-66311f60-a03f-4712-a8d2-8c22a7dcf149.png)

I get the following screen, which is weird:
![image](https://user-images.githubusercontent.com/41989385/200066606-907f0125-e4bd-4ccf-b84b-042c9c4a66fc.png)

I tried to install the GitHub app to my organization directly, but seems there is not way to do that since I can't find the app in the github marketplace.

I have been struggling for a week, and no solution yet...

This might not be the place to ask, but at least direct me to someone who can help.

Sending an email to support didn't help, so I need another way.

**Comment by nickytonline** [comment]
Closing as this is not related to Netlify or the Gatsby plugin. Please contact GitHub support for the issue you're facing, https://support.github.com .
