### ISSUE TITLE
[Bug] This plugin is running without enabling it

### ISSUE THREAD

**Issue by Goues** [netlify/netlify-plugin-gatsby#558]
### Summary

Hello,

I have many many sites in Netlify and yesterday, they started failing to build on:

```
Plugin "@netlify/plugin-gatsby" failed

Error: Could not load gatsby-config.js
Cannot find module './site_config.json'
Require stack:

/opt/build/repo/gatsby-config.js
/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/helpers/config.js
/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/helpers/cache.js
/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/index.js
In "onPreBuild" event in "@netlify/plugin-gatsby" from undefined
```

I never enabled this plugin and I don't want this plugin to run. Even if I create `./site_config.json` with `{}`, it keep failing on more and more errors. How do I disable this?

### Steps to reproduce

I have a site on Netlify and this plugin is just running for no apparent reason for the last 24 hours.

### Plugin version

I don't have this plugin, I don't want this plugin

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Gatsby info

```
zsh: command not found: gatsby
```

### Builds logs (or link to your logs)

```
10:20:42 PM:   Netlify Build                                                 
10:20:42 PM: ────────────────────────────────────────────────────────────────
10:20:42 PM: ​
10:20:42 PM: ❯ Version
10:20:42 PM:   @netlify/build 29.5.4
10:20:42 PM: ​
10:20:42 PM: ❯ Flags
10:20:42 PM:   baseRelDir: true
10:20:42 PM:   buildId: 63e2c08ccd7ae80097b8f789
10:20:42 PM:   deployId: 63e2c08c1f9c6e0008cc0f5a
10:20:42 PM: ​
10:20:42 PM: ❯ Current directory
10:20:42 PM:   /opt/build/repo
10:20:42 PM: ​
10:20:42 PM: ❯ Config file
10:20:42 PM:   No config file was defined: using default values.
10:20:42 PM: ​
10:20:42 PM: ❯ Context
10:20:42 PM:   production
10:20:42 PM: ​
10:20:42 PM: ❯ Installing plugins
10:20:42 PM:    - @netlify/plugin-gatsby@3.5.1
10:20:51 PM: ​
10:20:51 PM: ❯ Loading plugins
10:20:51 PM:    - @netlify/plugin-gatsby@3.5.1 from undefined
10:20:53 PM: ​
10:20:53 PM:   1. @netlify/plugin-gatsby (onPreBuild event)                  
10:20:53 PM: ────────────────────────────────────────────────────────────────
10:20:53 PM: ​
10:20:53 PM: No Gatsby cache found. Building fresh.
10:20:53 PM: ​
10:20:53 PM:   Plugin "@netlify/plugin-gatsby" failed                        
10:20:53 PM: ────────────────────────────────────────────────────────────────
10:20:53 PM: ​
10:20:53 PM:   Error message
10:20:53 PM:   Error: Could not load gatsby-config.js
10:20:53 PM:   Cannot find module './site_config.json'
10:20:53 PM:   Require stack:
10:20:53 PM:   - /opt/build/repo/gatsby-config.js
10:20:53 PM:   - /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/helpers/config.js
10:20:53 PM:   - /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/helpers/cache.js
10:20:53 PM:   - /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-gatsby/lib/index.js
```

**Comment by ascorbic** [comment]
Hi. `site_config.json` isn't something that this plugin is trying to load. Can you check if your `gatsby-config.js` is trying to load it?

**Comment by Goues** [comment]
The file is generated inside `npm run build` but this plugin runs before the pipeline even gets to run this command. So this plugin fails. I understand Netlify has bought Gatsby so it's trying to do something about the integration, but automatically enabling a plugin for all sites without knowing the sites feels wrong. I can't build any site because this plugin is running before `npm run build` and the files don't exist yet. Please, how do I disable it?

**Comment by sarahetter** [comment]
This has been fixed in the Netlify UI - You can navigate to Build Settings, and click the "Remove" button next to the Runtime section.
