### ISSUE TITLE
Use `utils.functions.add()`

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-gatsby#67]
`utils.functions.add(path)` can be used to copy a file or directory to the Functions source directory (such as `netlify/functions/`).

This plugin currently uses `fs.copy()` and `constants.FUNCTIONS_SRC` which works as well. However, using `utils.functions.add()` provides with some abstraction which will be helpful if we change some details on how Functions are configured in the future, such as providing a plugin-specific Functions directory as suggested in https://github.com/netlify/pod-workflow/issues/222

**Comment by ehmicky** [comment]
That's correct, good point.
I'm happy to change `utils.functions.add()` behavior to allow overwrites, since this seems to make more sense for plugin authors. What do you think?

**Comment by eduardoboucas** [comment]
> Yeah. I'm mostly interested in when we can use the private functions directory that @eduardoboucas is working on, and I'm guessing that will also require changes in the helper to specify which one

This will be possible with https://github.com/netlify/zip-it-and-ship-it/pull/537. The PR sheds some light on what this will look like from the zip-it-and-ship-it side.

Once that lands, we can either make plugins add their own private directories to the config via `onPreBuild` (e.g. `netlify-gatsby-plugin` would add `.netlify/netlify-gatsby-plugin-functions`), or we make Netlify Build look for a generic `.netlify/functions-internal` (name TBD) directory.

**Comment by ascorbic** [comment]
> Once that lands, we can either make plugins add their own private directories to the config via `onPreBuild` (e.g. `netlify-gatsby-plugin` would add `.netlify/netlify-gatsby-plugin-functions`), or we make Netlify Build look for a generic `.netlify/functions-internal` (name TBD) directory.

My opinions would be that a shared `internal-functions` directory would be best, otherwise it will be confusing about priorities for clashing names

**Comment by ascorbic** [comment]
Closing as we're handling this differently now
