### ISSUE TITLE
Add a `engines.node` field in `package.json`

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-gatsby#69]
When an `engines.node` field is present in `package.json`, our builds will show some nice error message when a site is using a Node.js version that's too old for this plugin. This provides with a better user experience (otherwise the plugin might crash in a more obscure way).

Would it make sense to add this field in `package.json`, based on the minimum Node.js version?

**Comment by erezrokah** [comment]
I believe the plugin has it here:
https://github.com/netlify/netlify-plugin-gatsby/blob/7d6fd6380cc573cfe43d47f1b47c4a307003abfb/plugin/package.json#L30

It would still be good to add it at the top level.

**Comment by ehmicky** [comment]
Oops, I did not notice this repository had two `package.json`! Sorry about the noise. :pray:
