### ISSUE TITLE
Be more clear that this library is deprecated. 

### ISSUE THREAD

**Issue by tony-gutierrez** [netlify/netlify-plugin-gatsby#725]
According to https://docs.netlify.com/integrations/frameworks/gatsby/?gatsby-version=adapters

This library is no longer used? gatsby-adapter-netlify is used instead?

**Comment by MarcL** [comment]
Hey @tony-gutierrez!

Thanks for raising this issue.

This plugin **isn't deprecated** and is still being actively developed (see #303 for example where we're supporting the new Netlify image CDN). We've still got the documentation for this [plugin here](https://docs.netlify.com/integrations/frameworks/gatsby/?gatsby-version=essential).

The [adapters](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/adapters/) are a new pattern we've adopted for Gatsby v5.12.0 and above to make it easy to deploy Gatsby to Netlify or any other platform. If you're planning on building a new Gatsby site then we'd suggest using those and then this plugin isn't needed. However, if you're using a version prior to Gatsby v5.12.0 then you'll need this plugin to deploy to Netlify.

I hope that clarifies things but let us know if you have any more questions.
