### ISSUE TITLE
Static HTML page doesn't update on deploy when data changes

### ISSUE THREAD

**Issue by qubis741** [netlify/netlify-plugin-gatsby#86]
Hello there,
I have a problem with this plugin, that static generated HTML page which loads as a first has cached old data. I am using Shopify as a source of data and I have set deploy to trigger on product create/update/deletion. So for example first second or 2 shows old list of products and then, when React hydrates, new list is loaded. When I clear cache in Netlify or when I update code with something on list page, new static site is generated. Is there any way to prevent static HTML sites to be cached via this plugin or to be regenerated when source data changes?

**Comment by ascorbic** [comment]
Hi. It certainly shouldn't be keeping the old version around: when you do a new build it should replace the generated file with a new one. Can you try and reproduce this locally? If you run `netlify build` using the netlify cli, does it do a build, and does it replace the HTML file? How about if you simply run `gatsby build` and `gatsby serve` locally? Does that update when you make a change?

**Comment by qubis741** [comment]
So I have found out what was wrong, I was using Gatsby incremental build and that was doing this problem, sorry for your trouble. If someone has same problem, here is more info:
https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#incremental-builds-in-oss
